language: php

dist: trusty

sudo: required

php:
    - 7.0

services:
    - memcache
    - redis-server

before-install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install

script:
    - vendor/bin/phpunit
