language: php

dist: trusty

php:
    - 7.0

sudo: required

services:
    - memcache
    - redis-server

before-install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
    - printf "\n" | pecl install -f redis
    - printf "\n" | pecl install -f memcached
    - composer install

script:
    - vendor/bin/phpunit
