language: php

dist: trusty

php:
    - 7.0

sudo: required

services:
    - memcache
    - redis-server

before-install:
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - pecl install redis
    - pecl install memcached
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit
